//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWL.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HWLEntities : DbContext
    {
        public HWLEntities()
            : base("name=HWLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<t_admin> t_admin { get; set; }
        public virtual DbSet<t_user> t_user { get; set; }
        public virtual DbSet<t_user_code> t_user_code { get; set; }
        public virtual DbSet<t_city> t_city { get; set; }
        public virtual DbSet<t_country> t_country { get; set; }
        public virtual DbSet<t_district> t_district { get; set; }
        public virtual DbSet<t_province> t_province { get; set; }
    }
}
