//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_app_version
    {
        public int id { get; set; }
        public string app_name { get; set; }
        public string app_version { get; set; }
        public string download_url { get; set; }
        public System.DateTime publish_time { get; set; }
        public System.DateTime update_time { get; set; }
    }
}
