//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_app_version
    {
        public int id { get; set; }
        public string app_name { get; set; }
        public string app_version { get; set; }
        public string download_url { get; set; }
        public System.DateTime publish_time { get; set; }
        public System.DateTime update_time { get; set; }
    }
}
