//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_near_circle_comment
    {
        public int id { get; set; }
        public int near_circle_id { get; set; }
        public int comment_user_id { get; set; }
        public string content_info { get; set; }
        public int reply_user_id { get; set; }
        public System.DateTime comment_time { get; set; }
    }
}
