//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_near_circle_image
    {
        public int id { get; set; }
        public int near_circle_id { get; set; }
        public int near_circle_user_id { get; set; }
        public string image_url { get; set; }
        public int width { get; set; }
        public int height { get; set; }
        public int width1 { get; set; }
        public int height1 { get; set; }
    }
}
