//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_near_circle
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public HWL.Entity.CircleContentType content_type { get; set; }
        public string content_info { get; set; }
        public string link_title { get; set; }
        public string link_url { get; set; }
        public string link_image { get; set; }
        public System.DateTime publish_time { get; set; }
        public int pos_id { get; set; }
        public double lon { get; set; }
        public double lat { get; set; }
        public int image_count { get; set; }
        public int comment_count { get; set; }
        public int like_count { get; set; }
    }
}
