//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_user_code
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string user_account { get; set; }
        public HWL.Entity.CodeType code_type { get; set; }
        public string code { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime expire_time { get; set; }
        public string remark { get; set; }
    }
}
