//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_user_pos
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string pos_details { get; set; }
        public double lon { get; set; }
        public double lat { get; set; }
        public string geohash_key { get; set; }
        public int country_id { get; set; }
        public int province_id { get; set; }
        public int city_id { get; set; }
        public int district_id { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime update_date { get; set; }
    }
}
