//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_user_friend
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int friend_user_id { get; set; }
        public string friend_user_remark { get; set; }
        public string friend_first_spell { get; set; }
        public System.DateTime add_time { get; set; }
    }
}
