//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HWL.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_user_friend
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public int friend_user_id { get; set; }
        public string friend_user_remark { get; set; }
        public string friend_first_spell { get; set; }
        public System.DateTime add_time { get; set; }
    }
}
